'use client';
import {useEffect,useMemo,useState} from 'react';
import {api,apiDownload,selectedLodge} from '@/lib/api';
import {useConfirmDialog} from './AppDialog';

type CatalogReport={id:string;name:string;family:string;formats:string[];schedulable:boolean;sensitive?:boolean;key:string};
type Generated={id:string;report_type:string;format:string;status:string;progress:number;row_count:number;sha256:string;created_at:string;metadata?:Record<string,unknown>;error?:string};
type Schedule={id:string;report_type:string;format:string;schedule:string;recipients:string[];attachments:string[];is_active:boolean;last_status?:string;next_run_at?:string|null};
type Saved={id:string;name:string;report_type:string;filters:Record<string,unknown>;is_shared:boolean};
type Preview={report_id:string;definition:CatalogReport;columns:string[];rows:unknown[][];kpis:Array<[string,unknown]>;trend:Array<{label:string;value:number}>;filters:Record<string,unknown>;total_rows:number;metadata:Record<string,unknown>};
type Approval={id:string;export_type:string;format:string;status:string;reason:string;requester:string;approved_by?:string|null;created_at:string;expires_at?:string|null};

function errText(e:unknown,fallback='Request failed'){return e instanceof Error?e.message:fallback}
function qs(filters:Record<string,string>,extra:Record<string,string>={}){const p=new URLSearchParams();Object.entries({...filters,...extra}).forEach(([k,v])=>{if(v)p.set(k,v)});return p.toString()}
function reportName(catalog:CatalogReport[],id:string){return catalog.find(x=>x.id===id)?.name||id}
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'good'|'warn'|'bad'|'gold'}){return <span className={`report-badge ${tone}`}>{children}</span>}

export function PremiumReportCenter(){
 const confirm=useConfirmDialog();
 const[catalog,setCatalog]=useState<CatalogReport[]>([]),[generated,setGenerated]=useState<Generated[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[saved,setSaved]=useState<Saved[]>([]),[approvals,setApprovals]=useState<Approval[]>([]);
 const[selected,setSelected]=useState('R-001'),[family,setFamily]=useState('All'),[preview,setPreview]=useState<Preview|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const[filters,setFilters]=useState<Record<string,string>>({start_date:'',end_date:'',status:'',member_id:'',tag:''});
 const selectedDef=catalog.find(x=>x.id===selected);const families=useMemo(()=>['All',...Array.from(new Set(catalog.map(x=>x.family)))],[catalog]);
 const visible=useMemo(()=>catalog.filter(x=>family==='All'||x.family===family),[catalog,family]);
 async function load(){setError('');try{const [c,g,s,v]=await Promise.all([api<{results:CatalogReport[]}>('/reports/catalog',{},selectedLodge()),api<{results:Generated[]}>('/reports/generated?limit=80',{},selectedLodge()),api<{results:Schedule[]}>('/reports/schedules',{},selectedLodge()),api<{results:Saved[]}>('/reports/saved',{},selectedLodge())]);setCatalog(c.results||[]);setGenerated(g.results||[]);setSchedules(s.results||[]);setSaved(v.results||[]);if(c.results?.length&&!c.results.some(x=>x.id===selected))setSelected(c.results[0].id);try{const a=await api<{results:Approval[]}>('/exports/approvals',{},selectedLodge());setApprovals(a.results||[])}catch{setApprovals([])}}catch(e){setError(errText(e,'Unable to load reporting workspace'))}}
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('lodgeflow:lodge-change',refresh);window.addEventListener('lodgeflow:sync-complete',refresh);return()=>{window.removeEventListener('lodgeflow:lodge-change',refresh);window.removeEventListener('lodgeflow:sync-complete',refresh)}},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function previewReport(id=selected){setLoading(true);setError('');setMessage('');try{const x=await api<Preview>(`/reports/preview/${id}?${qs(filters,{limit:'100'})}`,{},selectedLodge());setPreview(x);setSelected(id)}catch(e){setError(errText(e,'Report preview failed'))}finally{setLoading(false)}}
 async function exportNow(fmt:string){if(!selectedDef)return;setError('');try{await apiDownload(`/reports/generate/${selected}?${qs(filters,{format:fmt})}`,`${selected.toLowerCase()}-${new Date().toISOString().slice(0,10)}.${fmt}`,selectedLodge());setMessage(`${selectedDef.name} generated as ${fmt.toUpperCase()} with audit evidence.`);await load()}catch(e){const text=errText(e,'Export failed');setError(text.includes('report_approval_required')?'This report requires an approved sensitive-export request before download. Create an approval request below.':text)}}
 async function queueReport(){if(!selectedDef)return;setError('');try{const x=await api<{id:string;status:string;job_id:string}>(`/reports/generate/${selected}?${qs(filters,{format:selectedDef.formats[0]||'pdf',async:'1'})}`,{},selectedLodge());setMessage(`Background generation queued · job ${x.job_id||x.id}.`);await load()}catch(e){setError(errText(e,'Background generation failed'))}}
 async function saveView(){if(!selectedDef)return;const name=`${selectedDef.name} · ${new Date().toLocaleDateString()}`;try{await api('/reports/saved',{method:'POST',body:JSON.stringify({name,report_type:selected,filters,columns:preview?.columns||[],grouping:[],sorting:[],is_shared:false})},selectedLodge());setMessage('Private report view saved with its exact filters.');await load()}catch(e){setError(errText(e,'Save view failed'))}}
 async function loadSaved(v:Saved){setSelected(v.report_type);setFilters(f=>({...f,...Object.fromEntries(Object.entries(v.filters||{}).map(([k,val])=>[k,String(val??'')]))}));setMessage(`Loaded saved view “${v.name}”.`)}
 async function requestApproval(){if(!selectedDef)return;const reason=`Governed export of ${selectedDef.name}`;try{await api('/exports/approvals',{method:'POST',body:JSON.stringify({export_type:`report:${selected}`,format:selectedDef.formats[0]||'pdf',filters,reason})},selectedLodge());setMessage('Sensitive report approval requested. An authorized approver must review it before generation.');await load()}catch(e){setError(errText(e,'Approval request failed'))}}
 async function createSchedule(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,fd=new FormData(form);const recipients=String(fd.get('recipients')||'').split(',').map(x=>x.trim()).filter(Boolean);const attachments=String(fd.get('attachments')||'').split(',').map(x=>x.trim()).filter(Boolean);try{await api('/reports/schedules',{method:'POST',body:JSON.stringify({report_type:fd.get('report_type'),format:fd.get('format'),schedule:fd.get('schedule'),recipients,attachments,filters,is_active:true})},selectedLodge());form.reset();setMessage('Validated background schedule created.');await load()}catch(e){setError(errText(e,'Schedule creation failed'))}}
 async function scheduleAction(s:Schedule,action:'toggle'|'run'|'delete'){try{if(action==='run')await api(`/reports/schedules/${s.id}/run`,{method:'POST',body:'{}'},selectedLodge());else if(action==='delete'){if(!(await confirm.ask('Delete this scheduled report?',{title:'Delete report schedule',danger:true,confirmLabel:'Delete'})))return;await api(`/reports/schedules/${s.id}`,{method:'DELETE'},selectedLodge())}else await api(`/reports/schedules/${s.id}`,{method:'PATCH',body:JSON.stringify({is_active:!s.is_active})},selectedLodge());setMessage(action==='run'?'Schedule queued for an immediate controlled run.':action==='delete'?'Schedule deleted.':s.is_active?'Schedule paused.':'Schedule resumed.');await load()}catch(e){setError(errText(e,'Schedule operation failed'))}}
 const completed=generated.filter(x=>x.status==='completed').length,queued=generated.filter(x=>['queued','running'].includes(x.status)).length,failed=generated.filter(x=>x.status==='failed').length;
 return <div className="report-center">
  <section className="report-hero panel"><div><span className="eyebrow gold">Decision intelligence</span><h2>Professional reporting, without spreadsheet guesswork.</h2><p>Every preview is calculated from authorized server-side tenant data. Interactive and scheduled reports share the same definitions, filters, reconciliation rules and audit trail.</p><div className="report-hero-actions"><button className="primary" onClick={()=>void previewReport()} disabled={loading}>{loading?'Building preview…':'Preview selected report'}</button><button className="secondary" onClick={()=>void saveView()}>Save this view</button></div></div><div className="report-hero-metrics" aria-label="Report workspace status"><div><strong>{catalog.length}</strong><span>commercial reports</span></div><div><strong>{completed}</strong><span>generated outputs</span></div><div><strong>{schedules.filter(x=>x.is_active).length}</strong><span>active schedules</span></div><div><strong>{failed}</strong><span>failed outputs</span></div></div></section>
  {(error||message)&&<div className={`alert ${error?'error':'success'}`}>{error||message}</div>}
  <div className="report-layout">
   <aside className="panel report-library"><div className="report-section-head"><div><span className="eyebrow">Report library</span><h3>Commercial catalogue</h3></div><Badge tone="gold">{visible.length}</Badge></div><div className="report-family-tabs" role="tablist" aria-label="Report families">{families.map(x=><button key={x} className={family===x?'active':''} onClick={()=>setFamily(x)}>{x}</button>)}</div><div className="report-card-list">{visible.map(r=><button key={r.id} className={`report-card ${selected===r.id?'selected':''}`} onClick={()=>{setSelected(r.id);setPreview(null)}}><span className="report-id">{r.id}</span><strong>{r.name}</strong><small>{r.family} · {r.formats.map(x=>x.toUpperCase()).join(' / ')}</small><div>{r.schedulable&&<Badge tone="good">Schedulable</Badge>}{r.sensitive&&<Badge tone="warn">Sensitive</Badge>}</div></button>)}</div></aside>
   <main className="report-main">
    <section className="panel report-builder"><div className="report-section-head"><div><span className="eyebrow">Report designer</span><h3>{selectedDef?.name||'Select a report'}</h3><p>{selectedDef?.id} · {selectedDef?.family} · filters are disclosed in every generated output.</p></div>{selectedDef?.sensitive&&<Badge tone="warn">Approval governed</Badge>}</div><div className="report-filter-grid"><label><span>Start date</span><input type="date" value={filters.start_date} onChange={e=>setFilters({...filters,start_date:e.target.value})}/></label><label><span>End date</span><input type="date" value={filters.end_date} onChange={e=>setFilters({...filters,end_date:e.target.value})}/></label><label><span>Status</span><input value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} placeholder="Optional status filter"/></label><label><span>Tag / group</span><input value={filters.tag} onChange={e=>setFilters({...filters,tag:e.target.value})} placeholder="Optional tag"/></label></div><div className="report-action-row"><button className="primary" onClick={()=>void previewReport()} disabled={!selectedDef||loading}>Reconcile preview</button>{selectedDef?.formats.map(fmt=><button key={fmt} className="secondary" onClick={()=>void exportNow(fmt)}>Export {fmt.toUpperCase()}</button>)}<button className="secondary" onClick={()=>void queueReport()}>Generate in background</button>{selectedDef?.sensitive&&<button className="secondary" onClick={()=>void requestApproval()}>Request approval</button>}</div></section>
    <section className="panel report-preview" aria-live="polite"><div className="report-section-head"><div><span className="eyebrow">Reconciled preview</span><h3>{preview?preview.definition.name:'Choose filters, then preview'}</h3></div>{preview&&<Badge tone="good">{preview.total_rows} record{preview.total_rows===1?'':'s'}</Badge>}</div>{!preview?<div className="report-empty"><strong>No preview generated yet</strong><span>Preview before export to validate the reporting period, KPIs, detail rows and filter metadata.</span></div>:<><div className="report-metadata"><span>Tenant <b>{String(preview.metadata.tenant||'')}</b></span><span>Rows <b>{preview.total_rows}</b></span><span>Report ID <b>{preview.report_id}</b></span><span>Generated <b>{new Date(String(preview.metadata.generated_at)).toLocaleString()}</b></span></div>{preview.kpis?.length>0&&<div className="report-kpis">{preview.kpis.slice(0,8).map(([label,value])=><article key={label}><span>{label}</span><strong>{String(value)}</strong></article>)}</div>}{preview.trend?.length>0&&<AccessibleTrend rows={preview.trend}/>}<div className="table-scroll report-table"><table><thead><tr>{preview.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{preview.rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v===null||v===undefined||v===''?'—':String(v)}</td>)}</tr>)}</tbody></table></div>{preview.total_rows>preview.rows.length&&<small className="report-note">Showing the first {preview.rows.length} authorized rows. Full generation uses the complete server-side result set.</small>}</>}</section>
   </main>
  </div>
  <section className="report-bottom-grid"><article className="panel report-ops"><div className="report-section-head"><div><span className="eyebrow">Generated vault</span><h3>Stored, hashed outputs</h3></div><Badge tone={failed?'warn':'good'}>{queued} processing</Badge></div><div className="report-activity">{generated.slice(0,12).map(g=><div className="report-activity-row" key={g.id}><div><strong>{reportName(catalog,g.report_type)}</strong><small>{String(g.format).toUpperCase()} · {new Date(g.created_at).toLocaleString()} · {g.row_count} rows</small>{g.error&&<small className="report-error">{g.error}</small>}</div><div className="report-activity-actions"><Badge tone={g.status==='completed'?'good':g.status==='failed'?'bad':'warn'}>{g.status} {g.status==='running'?`${g.progress}%`:''}</Badge>{g.status==='completed'&&<button className="secondary" onClick={()=>void apiDownload(`/reports/generated/${g.id}/download`,String(g.metadata?.filename||`${g.report_type}.${g.format}`),selectedLodge())}>Download</button>}</div></div>)}</div>{!generated.length&&<div className="report-empty compact"><strong>No generated reports yet</strong><span>Completed background reports will appear here with file hashes and private downloads.</span></div>}</article>
   <article className="panel report-ops"><div className="report-section-head"><div><span className="eyebrow">Automation</span><h3>Scheduled report packs</h3></div><Badge tone="gold">Celery Beat</Badge></div><form className="report-schedule-form" onSubmit={createSchedule}><select name="report_type" required defaultValue=""><option value="">Schedulable report…</option>{catalog.filter(x=>x.schedulable).map(r=><option key={r.id} value={r.id}>{r.id} · {r.name}</option>)}</select><select name="format"><option>pdf</option><option>xlsx</option><option>csv</option></select><input name="schedule" required placeholder="0 8 1 * *" aria-label="Five field cron schedule"/><input name="recipients" required placeholder="secretary@example.org, treasurer@example.org"/><input name="attachments" placeholder="Optional report IDs: R-050,R-051"/><button className="primary">Create validated schedule</button></form><div className="report-activity">{schedules.slice(0,8).map(s=><div className="report-activity-row" key={s.id}><div><strong>{s.report_type} · {reportName(catalog,s.report_type)}</strong><small>{s.schedule} · {s.format.toUpperCase()} · {s.recipients.length} recipient(s){s.next_run_at?` · next ${new Date(s.next_run_at).toLocaleString()}`:''}</small></div><div className="report-activity-actions"><Badge tone={s.is_active?'good':'neutral'}>{s.is_active?'active':'paused'}</Badge><button className="secondary" onClick={()=>void scheduleAction(s,'run')} disabled={!s.is_active}>Run</button><button className="secondary" onClick={()=>void scheduleAction(s,'toggle')}>{s.is_active?'Pause':'Resume'}</button><button className="secondary danger" onClick={()=>void scheduleAction(s,'delete')}>Delete</button></div></div>)}</div></article>
   <article className="panel report-ops"><div className="report-section-head"><div><span className="eyebrow">Saved intelligence</span><h3>Reusable views</h3></div><Badge>{saved.length}</Badge></div><div className="report-activity">{saved.slice(0,12).map(v=><button className="report-saved" key={v.id} onClick={()=>void loadSaved(v)}><div><strong>{v.name}</strong><small>{v.report_type} · {v.is_shared?'Shared':'Private'}</small></div><span>Open →</span></button>)}</div>{!saved.length&&<div className="report-empty compact"><strong>No saved views</strong><span>Save a reconciled filter set to make recurring analysis faster.</span></div>}</article>
   <article className="panel report-ops"><div className="report-section-head"><div><span className="eyebrow">Governance</span><h3>Sensitive approvals</h3></div><Badge tone="warn">Dual control</Badge></div><div className="report-activity">{approvals.filter(a=>a.export_type.startsWith('report:')).slice(0,10).map(a=><div className="report-activity-row" key={a.id}><div><strong>{a.export_type.replace('report:','')} · {a.format.toUpperCase()}</strong><small>{a.reason||'No reason'} · {new Date(a.created_at).toLocaleString()}</small></div><Badge tone={a.status==='approved'?'good':a.status==='rejected'?'bad':'warn'}>{a.status}</Badge></div>)}</div>{!approvals.some(a=>a.export_type.startsWith('report:'))&&<div className="report-empty compact"><strong>No report approvals</strong><span>Sensitive compliance exports appear here when dual-control approval is required.</span></div>}</article>
  </section>{confirm.dialog}
 </div>
}

function AccessibleTrend({rows}:{rows:Array<{label:string;value:number}>}){const max=Math.max(1,...rows.map(x=>Number(x.value)||0));return <section className="report-trend" aria-label="Accessible trend visualization"><div className="report-section-head"><div><span className="eyebrow">Trend</span><h4>Labelled distribution</h4></div><small>Values are printed as text; meaning does not rely on color.</small></div><div className="report-bars">{rows.slice(0,12).map(x=><div className="report-bar-row" key={x.label} aria-label={`${x.label}: ${x.value}`}><span>{x.label}</span><div><i style={{width:`${Math.max(3,(Number(x.value)||0)/max*100)}%`}}/><b>{x.value}</b></div></div>)}</div></section>}
