'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {useConfirmDialog,useStepUpDialog} from './AppDialog';

type Tenant={id:string;name:string;plan:string};
type Row=Record<string,unknown>;
type Subscription={id:string;tenant:string;plan:string;status:string;provider:string;provider_customer_id:string;provider_subscription_id:string;last_synced_at?:string|null};
type Health={provider:string;mode:string;configured:boolean;healthy:boolean;credential_count:number};
type Overview={subscriptions:Subscription[];events:Row[];webhooks:Row[];payment_requests:Row[];provider_health:Health[];checkout_policy:Record<string,unknown>;summary:{active_subscriptions:number;past_due:number;webhook_quarantined:number;webhook_failed:number;payment_requests_pending:number}};
const empty:Overview={subscriptions:[],events:[],webhooks:[],payment_requests:[],provider_health:[],checkout_policy:{},summary:{active_subscriptions:0,past_due:0,webhook_quarantined:0,webhook_failed:0,payment_requests_pending:0}};

function statusClass(v:unknown){const s=String(v||'').toLowerCase();return ['active','trialing','processed','paid','healthy','completed'].includes(s)?'good':['failed','quarantined','past_due'].includes(s)?'danger':'warn'}
function short(v:unknown,n=22){const s=String(v??'—');return s.length>n?s.slice(0,n)+'…':s}

export function PremiumBillingOps({tenants}:{tenants:Tenant[]}){
 const[data,setData]=useState<Overview>(empty),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const stepUp=useStepUpDialog();const confirmDialog=useConfirmDialog();
 const load=useCallback(async()=>{setError('');try{setData(await api<Overview>('/platform/billing'))}catch(e){setError(e instanceof Error?e.message:'Unable to load revenue operations.')}},[]);useEffect(()=>{void load()},[load]);
 const plans=useMemo(()=>data.checkout_policy||{},[data.checkout_policy]);
 async function protectedAction<T>(fn:()=>Promise<T>){try{return await fn()}catch(e){if(e instanceof Error&&e.message==='step_up_required'){const identity=await stepUp.ask('Confirm your password and MFA code where enrolled. Billing mutations are protected by step-up authentication.',{title:'Verify billing administrator'});if(!identity)throw new Error('Sensitive action cancelled.');await api('/auth/step-up',{method:'POST',body:JSON.stringify(identity)});return fn()}throw e}}
 async function saveSubscription(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await protectedAction(()=>api('/platform/billing',{method:'POST',body:JSON.stringify({tenant_id:f.get('tenant_id'),provider:'stripe',plan:f.get('plan'),status:f.get('status'),provider_customer_id:f.get('provider_customer_id'),provider_subscription_id:f.get('provider_subscription_id')})}));setMessage('Subscription state saved with audit evidence.');e.currentTarget.reset();await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save subscription.')}finally{setBusy(false)}}
 async function saveCatalog(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const policy={annual:{stripe_price_id:String(f.get('annual')||'').trim()},monthly:{stripe_price_id:String(f.get('monthly')||'').trim()},enterprise:{stripe_price_id:String(f.get('enterprise')||'').trim()},trial:{stripe_price_id:String(f.get('trial')||'').trim()},success_url:String(f.get('success_url')||'').trim(),cancel_url:String(f.get('cancel_url')||'').trim(),portal_return_url:String(f.get('portal_return_url')||'').trim(),approved_return_origins:String(f.get('approved_return_origins')||'').split(',').map(x=>x.trim()).filter(Boolean)};try{await protectedAction(()=>api('/platform/billing',{method:'POST',body:JSON.stringify({action:'configure_checkout',policy})}));setMessage('Checkout catalog and approved return origins saved through the billing control plane.');await load()}catch(err){setError(err instanceof Error?err.message:'Unable to save checkout catalog.')}}
 async function replay(row:Row){const id=String(row.id||'');if(!id)return;const approved=await confirmDialog.ask('Replay this verified webhook? Idempotency controls remain active and the replay is audited.',{title:'Replay provider callback',danger:true,confirmLabel:'Replay safely'});if(!approved)return;try{await protectedAction(()=>api(`/platform/webhooks/${id}/replay`,{method:'POST',body:'{}'}));setMessage('Webhook replay completed without bypassing idempotency.');await load()}catch(err){setError(err instanceof Error?err.message:'Replay was not safely applicable.');await load()}}
 const health=(provider:string,mode:string)=>data.provider_health.find(x=>x.provider===provider&&x.mode===mode);
 return <div className="billing-premium">
  {error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}
  <section className="billing-hero"><div><span className="eyebrow">Revenue operations</span><h2>Billing confidence at a glance.</h2><p>Subscription state, provider readiness, settlement requests and webhook exceptions are visible without exposing credentials.</p><button className="primary" onClick={()=>void load()}>Refresh provider state</button></div><div className="billing-hero-orbit"><span>STRIPE</span><b>{data.summary.active_subscriptions}</b><small>active / trial subscriptions</small></div></section>
  <section className="billing-kpis"><article><span>Active subscriptions</span><b>{data.summary.active_subscriptions}</b><small>{data.summary.past_due} past due</small></article><article><span>Settlement requests</span><b>{data.summary.payment_requests_pending}</b><small>created / pending</small></article><article><span>Quarantine queue</span><b>{data.summary.webhook_quarantined}</b><small>requires operator review</small></article><article><span>Failed callbacks</span><b>{data.summary.webhook_failed}</b><small>retry or investigation</small></article></section>
  <section className="panel provider-readiness"><div className="panel-title"><div><span className="eyebrow">Encrypted provider vault</span><h3>Readiness matrix</h3><p>Only health metadata is rendered here. Secrets remain write-only and encrypted.</p></div></div><div className="provider-grid">{['stripe','paymongo','xendit'].map(provider=><article key={provider}><div className="provider-logo">{provider.slice(0,2).toUpperCase()}</div><div><b>{provider[0].toUpperCase()+provider.slice(1)}</b><small>Subscription / local payment integration</small></div><div className="mode-health">{['test','live'].map(mode=>{const h=health(provider,mode);return <span key={mode} className={`status-badge ${h?.healthy?'good':h?.configured?'warn':''}`}>{mode}: {h?.healthy?'healthy':h?.configured?'unchecked':'not configured'}</span>})}</div></article>)}</div></section>
  <div className="billing-two-col"><section className="panel billing-card"><span className="eyebrow">Subscription control</span><h3>Govern tenant billing state</h3><form className="console-form" onSubmit={saveSubscription}><label><span>Tenant</span><select name="tenant_id" required><option value="">Choose tenant…</option>{tenants.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span>Plan</span><select name="plan"><option>annual</option><option>monthly</option><option>enterprise</option><option>trial</option></select></label><label><span>Status</span><select name="status"><option>active</option><option>trialing</option><option>past_due</option><option>paused</option><option>cancelled</option><option>incomplete</option></select></label><label><span>Stripe customer ID</span><input name="provider_customer_id"/></label><label><span>Stripe subscription ID</span><input name="provider_subscription_id"/></label><div className="console-actions"><button className="primary" disabled={busy}>{busy?'Verifying…':'Save audited state'}</button></div></form></section><section className="panel billing-card"><span className="eyebrow">Checkout governance</span><h3>Plans & approved return origins</h3><form className="console-form" onSubmit={saveCatalog}><label><span>Annual price</span><input name="annual" defaultValue={String((plans.annual as Record<string,unknown>|undefined)?.stripe_price_id||'')} placeholder="price_…"/></label><label><span>Monthly price</span><input name="monthly" defaultValue={String((plans.monthly as Record<string,unknown>|undefined)?.stripe_price_id||'')} placeholder="price_…"/></label><label><span>Enterprise price</span><input name="enterprise" defaultValue={String((plans.enterprise as Record<string,unknown>|undefined)?.stripe_price_id||'')} placeholder="price_…"/></label><label><span>Trial price</span><input name="trial" defaultValue={String((plans.trial as Record<string,unknown>|undefined)?.stripe_price_id||'')} placeholder="price_…"/></label><label className="wide"><span>Success URL</span><input name="success_url" defaultValue={String(plans.success_url||'')} placeholder="https://app.example.com/settings?billing=success"/></label><label className="wide"><span>Cancel URL</span><input name="cancel_url" defaultValue={String(plans.cancel_url||'')} placeholder="https://app.example.com/settings?billing=cancelled"/></label><label className="wide"><span>Portal return URL</span><input name="portal_return_url" defaultValue={String(plans.portal_return_url||'')} placeholder="https://app.example.com/settings"/></label><label className="wide"><span>Approved origins</span><input name="approved_return_origins" defaultValue={Array.isArray(plans.approved_return_origins)?plans.approved_return_origins.join(', '):''} placeholder="https://app.example.com"/></label><div className="console-actions"><button className="primary">Save checkout policy</button></div></form></section></div>
  <section className="panel subscription-ledger"><div className="panel-title"><div><span className="eyebrow">Subscription ledger</span><h3>{data.subscriptions.length} tenant billing records</h3></div></div><div className="subscription-grid">{data.subscriptions.map(s=><article key={s.id}><div><b>{tenants.find(t=>t.id===String(s.tenant))?.name||String(s.tenant)}</b><small>{s.plan} · Stripe</small></div><div><span className={`status-badge ${statusClass(s.status)}`}>{s.status}</span><small>{s.last_synced_at?`Synced ${new Date(s.last_synced_at).toLocaleString()}`:'Manual state'}</small></div></article>)}</div></section>
  <div className="billing-two-col"><section className="panel provider-events"><div className="panel-title"><div><span className="eyebrow">Webhook reconciliation</span><h3>Exceptions & replay</h3><p>Verified callbacks can be replayed without bypassing idempotency or evidence history.</p></div></div><div className="event-stack">{data.webhooks.slice(0,35).map((w,i)=><article key={String(w.id||i)}><div><b>{String(w.provider||'provider')} · {short(w.event_type)}</b><small>{short(w.event_id,30)} · {String(w.mode||'live')}</small>{w.quarantine_reason?<span>{String(w.quarantine_reason)}</span>:null}</div><div><span className={`status-badge ${statusClass(w.status)}`}>{String(w.status||'received')}</span>{['failed','quarantined'].includes(String(w.status))&&<button className="secondary" onClick={()=>void replay(w)}>Safe replay</button>}</div></article>)}{!data.webhooks.length&&<div className="empty-state"><strong>No webhook activity yet</strong><span>Signed provider callbacks will appear here.</span></div>}</div></section><section className="panel provider-events"><div className="panel-title"><div><span className="eyebrow">Payment request lifecycle</span><h3>Persisted before settlement</h3><p>Provider links have a local tenant, amount, currency, mode and internal reference before asynchronous payment.</p></div></div><div className="event-stack">{data.payment_requests.slice(0,35).map((r,i)=><article key={String(r.id||i)}><div><b>{String(r.provider||'provider')} · {String(r.currency||'')} {String(r.amount||'')}</b><small>{short(r.internal_reference,28)}</small></div><span className={`status-badge ${statusClass(r.status)}`}>{String(r.status||'created')}</span></article>)}</div></section></div>
  <section className="panel provider-events"><div className="panel-title"><div><span className="eyebrow">Billing evidence</span><h3>Provider event history</h3></div></div><div className="event-stack billing-event-grid">{data.events.slice(0,50).map((e,i)=><article key={String(e.id||i)}><div><b>{String(e.provider||'provider')} · {short(e.event_type,32)}</b><small>{short(e.provider_reference,34)} · {String(e.mode||'live')}</small></div><div><span className={`status-badge ${statusClass(e.status)}`}>{String(e.status||'recorded')}</span>{e.amount?<small>{String(e.currency||'')} {String(e.amount)}</small>:null}</div></article>)}</div></section>
 {stepUp.dialog}{confirmDialog.dialog}
 </div>
}
