import Link from 'next/link';
import {PublicLeadForm} from './PublicLeadForm';

export type CMSItem={title?:string;body?:string;quote?:string;name?:string;label?:string;value?:string;price?:string};
export type CMSBlock={type:string;hidden?:boolean;eyebrow?:string;title?:string;body?:string;items?:CMSItem[];image_url?:string;alt_text?:string;form_key?:string;primary_label?:string;primary_href?:string;secondary_label?:string;secondary_href?:string};
export function CmsBlockRenderer({block:b,index=0}:{block:CMSBlock;index?:number}){if(b.hidden)return null;
 if(b.type==='hero')return <section className="hero hero-animated" data-reveal><div className="hero-copy"><span className="eyebrow gold">{b.eyebrow}</span><h1>{b.title}</h1><p>{b.body}</p><div className="hero-actions"><Link className="primary large" href={b.primary_href||'/login'}>{b.primary_label||'Open workspace'}</Link>{b.secondary_label&&<a className="secondary large" href={b.secondary_href||'#features'}>{b.secondary_label}</a>}</div><div className="trust-row"><span>Tenant-isolated</span><span>Role-controlled</span><span>Audited</span><span>Exportable</span></div></div><ProductPreview/></section>;
 if(b.type==='features'||b.type==='feature_grid')return <section id="features" className="marketing-section" data-reveal><span className="eyebrow">{b.eyebrow}</span><h2>{b.title}</h2><p>{b.body}</p><div className="feature-grid">{(b.items||[]).map((x,j)=><article key={x.title||j}><div className="feature-number">{String(j+1).padStart(2,'0')}</div><h3>{x.title}</h3><p>{x.body}</p></article>)}</div></section>;
 if(b.type==='statistics')return <section className="marketing-section" data-reveal><span className="eyebrow">{b.eyebrow}</span><h2>{b.title}</h2><div className="public-stat-grid">{(b.items||[]).map((x,j)=><article key={j}><strong>{x.value}</strong><span>{x.label||x.title}</span></article>)}</div></section>;
 if(b.type==='image_text'||b.type==='image_text_split')return <section className="marketing-section public-image-split" data-reveal>{b.image_url?<img src={b.image_url} alt={b.alt_text||''}/>:<div className="public-image-placeholder" aria-hidden="true"/>}<div><span className="eyebrow">{b.eyebrow}</span><h2>{b.title}</h2><p>{b.body}</p></div></section>;
 if(b.type==='pricing')return <section id="pricing" className="marketing-section" data-reveal><span className="eyebrow">{b.eyebrow||'Plans'}</span><h2>{b.title}</h2><div className="feature-grid">{(b.items||[]).map((x,j)=><article key={j}><h3>{x.title}</h3><strong className="price-value">{x.price}</strong><p>{x.body}</p></article>)}</div></section>;
 if(b.type==='security')return <section id="security" className="security-band" data-reveal><div><span className="eyebrow gold">{b.eyebrow}</span><h2>{b.title}</h2></div><div className="security-list">{(b.items||[]).map((x,j)=><p key={x.title||j}><b>{x.title}</b><span>{x.body}</span></p>)}</div></section>;
 if(b.type==='testimonials')return <section className="marketing-section" data-reveal><span className="eyebrow">{b.eyebrow}</span><h2>{b.title}</h2><div className="feature-grid">{(b.items||[]).map((x,j)=><article key={j}><p>“{x.quote||x.body}”</p><h3>{x.name||x.title}</h3></article>)}</div></section>;
 if(b.type==='faq')return <section className="marketing-section" data-reveal><span className="eyebrow">{b.eyebrow||'FAQ'}</span><h2>{b.title}</h2><div className="faq-list">{(b.items||[]).map((x,j)=><details key={j}><summary>{x.title}</summary><p>{x.body}</p></details>)}</div></section>;
 if(b.type==='lead_form')return <section className="marketing-section" data-reveal><span className="eyebrow">{b.eyebrow||'Contact'}</span><h2>{b.title}</h2><p>{b.body}</p>{b.form_key?<PublicLeadForm formKey={b.form_key} title={b.title}/>:<p>Form not configured.</p>}</section>;
 if(b.type==='rich_text')return <section className="marketing-section prose-section" data-reveal><span className="eyebrow">{b.eyebrow}</span><h2>{b.title}</h2><p>{b.body}</p></section>;
 if(b.type==='cta')return <section id={index===0?'pricing':undefined} className="cta" data-reveal><span className="eyebrow">{b.eyebrow}</span><h2>{b.title}</h2><p>{b.body}</p><Link className="primary large" href={b.primary_href||'/login'}>{b.primary_label||'Get started'}</Link></section>;
 return null;}
function ProductPreview(){return <div className="hero-product" data-parallax><div className="hero-window"><div className="window-top"><i/><i/><i/><span>Harmony Lodge · Dashboard</span></div><div className="mini-sidebar"><b>LF</b>{['Overview','Members','Meetings','Dues','Finance','Reports'].map(x=><span key={x}>{x}</span>)}</div><div className="mini-main"><div className="mini-head"><div><small>Lodge health</small><strong>Strong & steady</strong></div><em>86</em></div><div className="mini-kpis"><div><small>Active members</small><b>84</b><span>+4 this year</span></div><div><small>Dues collected</small><b>93%</b><span>12 outstanding</span></div><div><small>Avg. attendance</small><b>41</b><span>↑ 8%</span></div></div><div className="mini-chart">{[42,54,49,68,72,81,76,88].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div></div></div></div>}
