'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {AppShell} from '@/components/AppShell';
import {api} from '@/lib/api';
import {useTextPromptDialog} from '@/components/AppDialog';

type Row=Record<string,unknown>;
type Approval={id:string;export_type:string;format:string;status:string;reason:string;decision_reason?:string;requester:string|number;requester_name?:string;approved_by?:string|number|null;approver_name?:string;created_at:string;expires_at?:string|null;decided_at?:string|null};
type Chain={valid:boolean;checked:number;head_hash?:string;reason?:string;broken_event_id?:string};

function value(v:unknown){if(v===null||v===undefined||v==='')return '—';if(typeof v==='object')return JSON.stringify(v);return String(v)}
function CompactTable({rows}:{rows:Row[]}){const keys=useMemo(()=>{const preferred=['occurred_at','created_at','action','object_type','object_id','actor_name','export_type','format','row_count','requester','approver','result','sha256'];const all=new Set(rows.flatMap(r=>Object.keys(r)));return preferred.filter(k=>all.has(k)).slice(0,8)},[rows]);if(!rows.length)return <div className="compliance-empty"><b>No evidence matches these filters.</b><span>The audit boundary is still intact; broaden the filters to review earlier activity.</span></div>;return <div className="table-scroll"><table className="premium-table"><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id||i)}>{keys.map(k=><td key={k} title={value(r[k])}>{k==='sha256'?value(r[k]).slice(0,14)+'…':value(r[k])}</td>)}</tr>)}</tbody></table></div>}

export default function CompliancePage(){
 const promptDialog=useTextPromptDialog();
 const[audit,setAudit]=useState<Row[]>([]),[exports,setExports]=useState<Row[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[chain,setChain]=useState<Chain|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[mode,setMode]=useState<'audit'|'exports'|'approvals'>('audit');
 const[filters,setFilters]=useState({action:'',object_type:'',actor_id:'',date_from:'',date_to:''});
 const load=useCallback(async()=>{setError('');try{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));const[a,e,p,c]=await Promise.all([api<{results:Row[]}>(`/audit?${q}`),api<{results:Row[]}>('/compliance/exports'),api<{results:Approval[]}>('/exports/approvals'),api<Chain>('/audit/verify')]);setAudit(a.results);setExports(e.results);setApprovals(p.results);setChain(c)}catch(e){setError(e instanceof Error?e.message:'Unable to load compliance evidence.')}},[filters]);
 useEffect(()=>{void load()},[load]);
 async function requestApproval(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/exports/approvals',{method:'POST',body:JSON.stringify({export_type:f.get('export_type'),format:f.get('format'),reason:f.get('reason'),filters:{}})});setMessage('Sensitive export approval submitted with an expiry boundary.');e.currentTarget.reset();await load()}catch(err){setError(err instanceof Error?err.message:'Approval request failed.')}}
 async function decide(id:string,decision:'approved'|'rejected'){const reason=await promptDialog.ask(`${decision==='approved'?'Approval':'Rejection'} rationale is required for the evidence record.`,{title:decision==='approved'?'Approve sensitive export':'Reject sensitive export',confirmLabel:decision==='approved'?'Approve with evidence':'Reject with evidence'});if(!reason?.trim())return;try{await api(`/exports/approvals/${id}`,{method:'POST',body:JSON.stringify({decision,reason:reason.trim()})});setMessage(`Request ${decision}. The decision is now part of the audit trail.`);await load()}catch(err){setError(err instanceof Error?err.message:'Decision failed.')}}
 const pending=approvals.filter(x=>x.status==='pending').length;
 return <AppShell><div className="compliance-page">
  <section className="compliance-hero"><div><span className="eyebrow">Compliance command centre</span><h1>Evidence integrity, without the audit scramble.</h1><p>Review immutable change evidence, governed exports and dual-control decisions from one tenant-scoped workspace.</p><div className="hero-actions"><button className="primary" onClick={()=>void load()}>Refresh evidence</button><span className={`integrity-chip ${chain?.valid?'good':'warn'}`}><i/>{chain?.valid?'Hash chain verified':'Integrity review required'}</span></div></div><div className="compliance-score"><small>Evidence events verified</small><strong>{chain?.checked??'—'}</strong><span>{chain?.head_hash?`Head ${chain.head_hash.slice(0,12)}…`:(chain?.reason||'Verification pending')}</span></div></section>
  {error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}
  <section className="compliance-kpis"><article><span>Audit evidence</span><b>{audit.length}</b><small>Current filtered review set</small></article><article><span>Export evidence</span><b>{exports.length}</b><small>Hashes, counts and approval linkage</small></article><article><span>Pending decisions</span><b>{pending}</b><small>Dual-control queue</small></article><article><span>Integrity</span><b>{chain?.valid?'Verified':'Review'}</b><small>Append-only hash chain</small></article></section>
  <div className="compliance-tabs"><button className={mode==='audit'?'active':''} onClick={()=>setMode('audit')}>Audit trail</button><button className={mode==='exports'?'active':''} onClick={()=>setMode('exports')}>Export history</button><button className={mode==='approvals'?'active':''} onClick={()=>setMode('approvals')}>Sensitive approvals</button></div>
  {mode==='audit'&&<><section className="panel compliance-filter"><div><span className="eyebrow">Evidence explorer</span><h3>Filter the immutable trail</h3><p>Tenant scope is enforced on the server before these records are returned.</p></div><div className="filter-grid"><label><span>Action / module</span><input value={filters.action} onChange={e=>setFilters({...filters,action:e.target.value})} placeholder="finance. / settings."/></label><label><span>Object type</span><input value={filters.object_type} onChange={e=>setFilters({...filters,object_type:e.target.value})} placeholder="Payment"/></label><label><span>Actor ID</span><input value={filters.actor_id} onChange={e=>setFilters({...filters,actor_id:e.target.value})}/></label><label><span>From</span><input type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/></label><label><span>To</span><input type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/></label></div></section><section className="panel evidence-panel"><div className="panel-title"><div><span className="eyebrow">Append-only evidence</span><h3>Protected business activity</h3></div><span className="evidence-count">{audit.length} shown</span></div><CompactTable rows={audit}/></section></>}
  {mode==='exports'&&<section className="panel evidence-panel"><div className="panel-title"><div><span className="eyebrow">Controlled data movement</span><h3>Export evidence ledger</h3><p>Every completed export records filters, row count, requester, approver and SHA-256 evidence.</p></div></div><CompactTable rows={exports}/></section>}
  {mode==='approvals'&&<div className="approval-layout"><section className="panel"><span className="eyebrow">Request controlled export</span><h3>State the business reason first</h3><form className="compliance-form" onSubmit={requestApproval}><label><span>Export</span><select name="export_type"><option value="members">Member data</option><option value="finance">Finance data</option><option value="audit">Audit evidence</option><option value="meetings">Meetings</option></select></label><label><span>Format</span><select name="format"><option>xlsx</option><option>pdf</option><option>csv</option></select></label><label className="wide"><span>Reason</span><textarea name="reason" minLength={8} required placeholder="Explain the legitimate administrative purpose…"/></label><button className="primary">Submit for approval</button></form></section><section className="panel"><span className="eyebrow">Dual-control queue</span><h3>Decision evidence</h3><div className="approval-stack">{approvals.map(a=><article key={a.id}><div><b>{a.export_type} · {a.format.toUpperCase()}</b><small>{a.reason}</small><span>Requested by {a.requester_name||String(a.requester)} · Expires {a.expires_at?new Date(a.expires_at).toLocaleString():'—'}</span>{a.approver_name?<span>Decision by {a.approver_name}{a.decision_reason?` · ${a.decision_reason}`:''}</span>:null}</div><div><span className={`status-badge ${a.status==='approved'?'good':a.status==='pending'?'warn':''}`}>{a.status}</span>{a.status==='pending'&&<div className="approval-actions"><button className="secondary" onClick={()=>void decide(a.id,'rejected')}>Reject</button><button className="primary" onClick={()=>void decide(a.id,'approved')}>Approve</button></div>}</div></article>)}{!approvals.length&&<div className="compliance-empty"><b>No approval requests</b><span>Controlled requests will appear here with requester and expiry evidence.</span></div>}</div></section></div>}
 {promptDialog.dialog}
 </div></AppShell>
}
