# Generated for LodgeFlow production release. Review with `makemigrations --check` in CI.
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('lodge_number', models.CharField(max_length=80, blank=True)),
                ('jurisdiction', models.CharField(max_length=160, blank=True)),
                ('plan', models.CharField(max_length=40, default='annual')),
                ('locale', models.CharField(max_length=16, default='en')),
                ('timezone', models.CharField(max_length=64, default='UTC')),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='user_memberships')),
                ('user', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tenant_memberships')),
                ('role', models.CharField(max_length=40, choices=[('owner', 'owner'), ('admin', 'admin'), ('secretary', 'secretary'), ('treasurer', 'treasurer'), ('membership', 'membership'), ('mentor', 'mentor'), ('document_manager', 'document_manager'), ('auditor', 'auditor'), ('viewer', 'viewer'), ('custom', 'custom')], default='viewer')),
                ('custom_permissions', models.JSONField(default=list, blank=True)),
                ('mfa_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['tenant', 'user'], name='uniq_user_tenant')]},
        ),
        migrations.CreateModel(
            name='LodgeProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField('platform_core.tenant', on_delete=models.CASCADE, related_name='profile')),
                ('address', models.TextField(blank=True)),
                ('meeting_schedule', models.JSONField(default=dict, blank=True)),
                ('letterhead', models.TextField(blank=True)),
                ('signature_blocks', models.JSONField(default=list, blank=True)),
                ('custom_fields', models.JSONField(default=list, blank=True)),
                ('retention_policy', models.JSONField(default=dict, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='members')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True)),
                ('phone', models.CharField(max_length=40, blank=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(max_length=24, choices=[('active', 'active'), ('inactive', 'inactive'), ('demitted', 'demitted'), ('suspended', 'suspended'), ('deceased', 'deceased'), ('candidate', 'candidate')], default='active')),
                ('degree', models.CharField(max_length=8, choices=[('none', 'none'), ('EA', 'EA'), ('FC', 'FC'), ('MM', 'MM')], default='none')),
                ('joined_on', models.DateField(null=True, blank=True)),
                ('initiated_on', models.DateField(null=True, blank=True)),
                ('passed_on', models.DateField(null=True, blank=True)),
                ('raised_on', models.DateField(null=True, blank=True)),
                ('date_of_birth', models.DateField(null=True, blank=True)),
                ('tags', models.JSONField(default=list, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('custom_data', models.JSONField(default=dict, blank=True)),
                ('is_dues_exempt', models.BooleanField(default=False)),
                ('custom_dues_amount', models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)),
            ],
            options={'indexes': [models.Index(fields=['tenant', 'last_name', 'first_name'], name='lf_member_name_idx'), models.Index(fields=['tenant', 'status'], name='lf_member_status_idx'), models.Index(fields=['tenant', 'email'], name='lf_member_email_idx')]},
        ),
        migrations.CreateModel(
            name='OfficerTerm',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='officer_terms')),
                ('member', models.ForeignKey('platform_core.member', on_delete=models.CASCADE, related_name='officer_terms')),
                ('office', models.CharField(max_length=120)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(null=True, blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('successor', models.ForeignKey('platform_core.member', on_delete=models.SET_NULL, null=True, blank=True, related_name='successor_terms')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='candidates')),
                ('member', models.OneToOneField('platform_core.member', on_delete=models.CASCADE, related_name='candidate_profile')),
                ('stage', models.CharField(max_length=80, default='enquiry')),
                ('stage_order', models.PositiveIntegerField(default=0)),
                ('mentor', models.ForeignKey('platform_core.member', on_delete=models.SET_NULL, null=True, blank=True, related_name='mentees')),
                ('target_degree_date', models.DateField(null=True, blank=True)),
                ('proficiency_date', models.DateField(null=True, blank=True)),
                ('referred_by', models.CharField(max_length=160, blank=True)),
                ('status', models.CharField(max_length=40, default='active')),
                ('stage_history', models.JSONField(default=list, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTask',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE)),
                ('candidate', models.ForeignKey('platform_core.candidate', on_delete=models.CASCADE, related_name='tasks')),
                ('title', models.CharField(max_length=200)),
                ('due_on', models.DateField(null=True, blank=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='meetings')),
                ('title', models.CharField(max_length=180)),
                ('meeting_type', models.CharField(max_length=30, choices=[('stated', 'stated'), ('special', 'special'), ('degree', 'degree'), ('social', 'social'), ('committee', 'committee'), ('other', 'other')], default='stated')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(null=True, blank=True)),
                ('location', models.CharField(max_length=240, blank=True)),
                ('agenda', models.JSONField(default=list, blank=True)),
                ('business_items', models.JSONField(default=list, blank=True)),
                ('communications', models.JSONField(default=list, blank=True)),
                ('approved_bills', models.JSONField(default=list, blank=True)),
                ('status', models.CharField(max_length=30, default='scheduled')),
                ('recurrence_rule', models.CharField(max_length=255, blank=True)),
                ('education_minutes', models.PositiveIntegerField(default=0)),
                ('business_minutes', models.PositiveIntegerField(default=0)),
                ('fellowship_minutes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE)),
                ('meeting', models.ForeignKey('platform_core.meeting', on_delete=models.CASCADE, related_name='attendance')),
                ('member', models.ForeignKey('platform_core.member', on_delete=models.CASCADE, related_name='attendance')),
                ('status', models.CharField(max_length=24, default='present')),
                ('checked_in_at', models.DateTimeField(null=True, blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['meeting', 'member'], name='uniq_meeting_member_attendance')]},
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='visitors')),
                ('meeting', models.ForeignKey('platform_core.meeting', on_delete=models.CASCADE, related_name='visitors')),
                ('name', models.CharField(max_length=180)),
                ('home_lodge', models.CharField(max_length=180, blank=True)),
                ('lodge_number', models.CharField(max_length=80, blank=True)),
                ('jurisdiction', models.CharField(max_length=160, blank=True)),
                ('email', models.EmailField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinuteVersion',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE)),
                ('meeting', models.ForeignKey('platform_core.meeting', on_delete=models.CASCADE, related_name='minute_versions')),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(max_length=20, choices=[('draft', 'draft'), ('review', 'review'), ('approved', 'approved'), ('locked', 'locked')], default='draft')),
                ('body', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)),
                ('locked_at', models.DateTimeField(null=True, blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['meeting', 'version'], name='uniq_meeting_minute_version')]},
        ),
        migrations.CreateModel(
            name='DuesCycle',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='dues_cycles')),
                ('name', models.CharField(max_length=120)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_on', models.DateField()),
                ('standard_amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('late_fee', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('proration_enabled', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuesAssessment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE)),
                ('member', models.ForeignKey('platform_core.member', on_delete=models.CASCADE, related_name='dues_assessments')),
                ('cycle', models.ForeignKey('platform_core.duescycle', on_delete=models.CASCADE, related_name='assessments')),
                ('amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('late_fee', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('waived_amount', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('paid_amount', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('status', models.CharField(max_length=20, choices=[('open', 'open'), ('partial', 'partial'), ('paid', 'paid'), ('waived', 'waived'), ('overdue', 'overdue')], default='open')),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['member', 'cycle'], name='uniq_member_dues_cycle')]},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='payments')),
                ('member', models.ForeignKey('platform_core.member', on_delete=models.SET_NULL, null=True, blank=True, related_name='payments')),
                ('assessment', models.ForeignKey('platform_core.duesassessment', on_delete=models.SET_NULL, null=True, blank=True, related_name='payments')),
                ('amount', models.DecimalField(max_digits=12, decimal_places=2)),
                ('currency', models.CharField(max_length=3, default='PHP')),
                ('method', models.CharField(max_length=40, default='manual')),
                ('provider', models.CharField(max_length=40, blank=True)),
                ('provider_reference', models.CharField(max_length=180, blank=True)),
                ('receipt_number', models.CharField(max_length=80)),
                ('paid_at', models.DateTimeField(default=timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['tenant', 'receipt_number'], name='uniq_tenant_receipt')]},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='expenses')),
                ('meeting', models.ForeignKey('platform_core.meeting', on_delete=models.SET_NULL, null=True, blank=True, related_name='expenses')),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(max_digits=12, decimal_places=2)),
                ('currency', models.CharField(max_length=3, default='PHP')),
                ('incurred_on', models.DateField()),
                ('vendor', models.CharField(max_length=180, blank=True)),
                ('receipt_path', models.CharField(max_length=500, blank=True)),
                ('is_charity', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='documents')),
                ('title', models.CharField(max_length=240)),
                ('folder', models.CharField(max_length=240, blank=True)),
                ('tags', models.JSONField(default=list, blank=True)),
                ('file_path', models.CharField(max_length=500, blank=True)),
                ('mime_type', models.CharField(max_length=120, blank=True)),
                ('content', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict, blank=True)),
                ('template_key', models.CharField(max_length=80, blank=True)),
                ('created_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationCampaign',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='campaigns')),
                ('name', models.CharField(max_length=180)),
                ('channel', models.CharField(max_length=20, default='email')),
                ('subject', models.CharField(max_length=240, blank=True)),
                ('body', models.TextField()),
                ('segment', models.JSONField(default=dict, blank=True)),
                ('scheduled_for', models.DateTimeField(null=True, blank=True)),
                ('status', models.CharField(max_length=30, default='draft')),
                ('created_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE)),
                ('campaign', models.ForeignKey('platform_core.communicationcampaign', on_delete=models.CASCADE, related_name='deliveries')),
                ('member', models.ForeignKey('platform_core.member', on_delete=models.SET_NULL, null=True, blank=True)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30, default='queued')),
                ('provider_id', models.CharField(max_length=180, blank=True)),
                ('error', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, null=True, blank=True, related_name='email_templates')),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('subject', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('merge_fields', models.JSONField(default=list, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['tenant', 'key'], name='uniq_template_tenant_key', nulls_distinct=False)]},
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='report_schedules')),
                ('report_type', models.CharField(max_length=80)),
                ('format', models.CharField(max_length=10, default='pdf')),
                ('schedule', models.CharField(max_length=120)),
                ('recipients', models.JSONField(default=list, blank=True)),
                ('filters', models.JSONField(default=dict, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('occurred_at', models.DateTimeField(default=timezone.now, db_index=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.SET_NULL, null=True, blank=True, related_name='audit_events')),
                ('actor', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(max_length=120, blank=True)),
                ('object_id', models.CharField(max_length=80, blank=True)),
                ('request_id', models.CharField(max_length=80, blank=True)),
                ('ip_hash', models.CharField(max_length=128, blank=True)),
                ('user_agent', models.CharField(max_length=255, blank=True)),
                ('before', models.JSONField(default=dict, blank=True)),
                ('after', models.JSONField(default=dict, blank=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('prev_hash', models.CharField(max_length=64, blank=True)),
                ('event_hash', models.CharField(max_length=64, blank=True)),
            ],
            options={'ordering': ['-occurred_at'], 'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='lf_audit_tenant_time_idx'), models.Index(fields=['action', 'occurred_at'], name='lf_audit_action_time_idx')]},
        ),
        migrations.CreateModel(
            name='ExportEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='export_events')),
                ('actor', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)),
                ('export_type', models.CharField(max_length=80)),
                ('format', models.CharField(max_length=12)),
                ('filters', models.JSONField(default=dict, blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='approved_exports')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, null=True, blank=True, related_name='feature_flags')),
                ('key', models.SlugField(max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict, blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['tenant', 'key'], name='uniq_feature_flag_tenant', nulls_distinct=False)]},
        ),
        migrations.CreateModel(
            name='EncryptedCredential',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, null=True, blank=True, related_name='credentials')),
                ('provider', models.CharField(max_length=60)),
                ('mode', models.CharField(max_length=10, default='test')),
                ('ciphertext', models.TextField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('health_status', models.CharField(max_length=40, default='unchecked')),
                ('last_checked_at', models.DateTimeField(null=True, blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['tenant', 'provider', 'mode'], name='uniq_provider_credential', nulls_distinct=False)]},
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=60)),
                ('event_id', models.CharField(max_length=180)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.SET_NULL, null=True, blank=True)),
                ('event_type', models.CharField(max_length=120, blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=30, default='received')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(null=True, blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['provider', 'event_id'], name='uniq_provider_event')]},
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=180)),
                ('title', models.CharField(max_length=240)),
                ('status', models.CharField(max_length=20, default='draft')),
                ('blocks', models.JSONField(default=list, blank=True)),
                ('meta_title', models.CharField(max_length=240, blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og', models.JSONField(default=dict, blank=True)),
                ('schema', models.JSONField(default=dict, blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('locale', models.CharField(max_length=16, default='en')),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['slug', 'locale'], name='uniq_cms_slug_locale')]},
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=300, unique=True)),
                ('destination', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(default=301)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=30, default='banner')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(null=True, blank=True)),
                ('ends_at', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ABExperiment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('variants', models.JSONField(default=list)),
                ('weights', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ABAssignment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey('platform_core.abexperiment', on_delete=models.CASCADE, related_name='assignments')),
                ('subject_key', models.CharField(max_length=180)),
                ('variant', models.CharField(max_length=80)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.SET_NULL, null=True, blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['experiment', 'subject_key'], name='uniq_ab_assignment')]},
        ),
        migrations.CreateModel(
            name='ABExposure',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey('platform_core.abassignment', on_delete=models.CASCADE, related_name='exposures')),
                ('event', models.CharField(max_length=80, default='view')),
                ('metadata', models.JSONField(default=dict, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformRoleAssignment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='platform_roles')),
                ('role', models.CharField(max_length=40, choices=[('super_admin', 'super_admin'), ('support_admin', 'support_admin'), ('billing_admin', 'billing_admin'), ('compliance_auditor', 'compliance_auditor'), ('operator_devops', 'operator_devops')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['user', 'role'], name='uniq_platform_user_role')]},
        ),
        migrations.CreateModel(
            name='CustomRoleDefinition',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='custom_roles')),
                ('name', models.CharField(max_length=120)),
                ('permissions', models.JSONField(default=list)),
                ('approval_requirements', models.JSONField(default=dict, blank=True)),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['tenant', 'name'], name='uniq_custom_role_name')]},
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('items', models.JSONField(default=list)),
                ('locale', models.CharField(max_length=16, default='en')),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['key', 'locale'], name='uniq_nav_key_locale')]},
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('file_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=120, blank=True)),
                ('alt_text', models.CharField(max_length=300, blank=True)),
                ('accessibility_tags', models.JSONField(default=list, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('fields', models.JSONField(default=list)),
                ('routing', models.JSONField(default=dict, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSubmission',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey('platform_core.leadform', on_delete=models.PROTECT, related_name='submissions')),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=30, default='new')),
                ('source', models.CharField(max_length=240, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField('platform_core.tenant', on_delete=models.CASCADE, related_name='subscription')),
                ('provider', models.CharField(max_length=30, default='stripe')),
                ('provider_customer_id', models.CharField(max_length=180, blank=True)),
                ('provider_subscription_id', models.CharField(max_length=180, blank=True)),
                ('plan', models.CharField(max_length=60, default='annual')),
                ('status', models.CharField(max_length=40, default='active')),
                ('current_period_end', models.DateTimeField(null=True, blank=True)),
                ('trial_ends_at', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.SET_NULL, null=True, blank=True, related_name='billing_events')),
                ('provider', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=120)),
                ('provider_reference', models.CharField(max_length=180, blank=True)),
                ('amount', models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)),
                ('currency', models.CharField(max_length=3, blank=True)),
                ('payload', models.JSONField(default=dict, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='impersonations_started')),
                ('target_user', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='impersonations_received')),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE)),
                ('reason', models.TextField()),
                ('started_at', models.DateTimeField(default=timezone.now)),
                ('ended_at', models.DateTimeField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemJob',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.SET_NULL, null=True, blank=True, related_name='jobs')),
                ('kind', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=30, default='queued')),
                ('payload', models.JSONField(default=dict, blank=True)),
                ('result', models.JSONField(default=dict, blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(null=True, blank=True)),
                ('started_at', models.DateTimeField(null=True, blank=True)),
                ('finished_at', models.DateTimeField(null=True, blank=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='mfa_devices')),
                ('name', models.CharField(max_length=120, default='Authenticator')),
                ('secret_ciphertext', models.TextField()),
                ('backup_codes_hash', models.JSONField(default=list, blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('last_used_counter', models.BigIntegerField(default=-1)),
                ('confirmed_at', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportApprovalRequest',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='export_approvals')),
                ('requester', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='export_requests')),
                ('export_type', models.CharField(max_length=80)),
                ('format', models.CharField(max_length=12)),
                ('filters', models.JSONField(default=dict, blank=True)),
                ('status', models.CharField(max_length=20, default='pending')),
                ('approved_by', models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='export_approvals_given')),
                ('decided_at', models.DateTimeField(null=True, blank=True)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='milestones')),
                ('member', models.ForeignKey('platform_core.member', on_delete=models.CASCADE, related_name='milestones', null=True, blank=True)),
                ('kind', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('milestone_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('recurring_yearly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, related_name='participation_records')),
                ('member', models.ForeignKey('platform_core.member', on_delete=models.CASCADE, related_name='participation_records')),
                ('meeting', models.ForeignKey('platform_core.meeting', on_delete=models.SET_NULL, null=True, blank=True, related_name='participation_records')),
                ('kind', models.CharField(max_length=60)),
                ('points', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(max_length=255, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyReceipt',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey('platform_core.tenant', on_delete=models.CASCADE, null=True, blank=True, related_name='idempotency_receipts')),
                ('user_id', models.BigIntegerField(null=True, blank=True)),
                ('key', models.CharField(max_length=80)),
                ('method', models.CharField(max_length=12)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('content_type', models.CharField(max_length=120, blank=True)),
                ('response_body', models.BinaryField(blank=True, default=bytes)),
                ('expires_at', models.DateTimeField()),
            ],
            options={'constraints': [models.UniqueConstraint(fields=['tenant', 'user_id', 'key'], name='uniq_tenant_user_idem_key', nulls_distinct=False)], 'indexes': [models.Index(fields=['expires_at'], name='lf_idem_expiry_idx'), models.Index(fields=['tenant', 'key'], name='lf_idem_tenant_key_idx')]},
        ),
    ]
