'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';import {bindOfflinePrincipal} from '@/lib/offline';
type Setup={device_id:string;secret:string;otpauth_uri:string};
export default function MFA(){
 const[setup,setSetup]=useState<Setup|null>(null),[enroll,setEnroll]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{const needs=sessionStorage.getItem('lodgeflow:mfa-enroll')==='1';setEnroll(needs);if(needs){setLoading(true);api<Setup>('/mfa/setup',{method:'POST',body:'{}'},'').then(setSetup).catch(e=>setMessage(e instanceof Error?e.message:'Unable to prepare MFA enrollment')).finally(()=>setLoading(false))}},[]);
 async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage('');setLoading(true);const f=new FormData(e.currentTarget);try{const result=await api<{user?:{id:string|number}}>('/mfa/verify',{method:'POST',body:JSON.stringify({code:String(f.get('code')||''),device_id:setup?.device_id})},'');if(result.user?.id)await bindOfflinePrincipal(result.user.id);sessionStorage.removeItem('lodgeflow:mfa-enroll');location.assign('/dashboard')}catch(e){setMessage(e instanceof Error?e.message:'Verification failed')}finally{setLoading(false)}}
 return <main className="auth-page"><form className="auth-card" onSubmit={verify}><div className="brand-mark">LF</div><span className="eyebrow">Multi-factor security</span><h1>{enroll?'Secure your account':'Verify it’s you'}</h1>{enroll?<><p>Add this account to your authenticator app, then enter the current six-digit code.</p>{loading&&!setup&&<div className="skeleton-line"/>}{setup&&<div className="mfa-secret"><small>Authenticator secret</small><code>{setup.secret}</code><details><summary>Advanced setup URI</summary><code>{setup.otpauth_uri}</code></details></div>}</>:<p>Enter the current code from your authenticator app.</p>}<label>6-digit code<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required autoFocus/></label><button className="primary large" disabled={loading||Boolean(enroll&&!setup)}>{loading?'Verifying…':'Continue securely'}</button>{message&&<div className="alert error">{message}</div>}</form></main>
}